In [6]:
print("hello")

hello


In [12]:
import numpy as np
arr=np.arange(0,11,1)
arr[0]
print(arr[1:])

[ 1  2  3  4  5  6  7  8  9 10]


In [13]:
aa=np.arange(12,100,1.2)
print(aa)

[12.  13.2 14.4 15.6 16.8 18.  19.2 20.4 21.6 22.8 24.  25.2 26.4 27.6
 28.8 30.  31.2 32.4 33.6 34.8 36.  37.2 38.4 39.6 40.8 42.  43.2 44.4
 45.6 46.8 48.  49.2 50.4 51.6 52.8 54.  55.2 56.4 57.6 58.8 60.  61.2
 62.4 63.6 64.8 66.  67.2 68.4 69.6 70.8 72.  73.2 74.4 75.6 76.8 78.
 79.2 80.4 81.6 82.8 84.  85.2 86.4 87.6 88.8 90.  91.2 92.4 93.6 94.8
 96.  97.2 98.4 99.6]


In [15]:
lol=np.arange(0,100,1)[12:]
lol

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
       46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62,
       63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79,
       80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
       97, 98, 99])

In [18]:

array=np.arange(1,10)
array[4:]

array([5, 6, 7, 8, 9])

In [20]:
array=np.arange(1,10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
s=np.arange(0,20)
slide=s[1:11]

In [28]:
slide[:]=69

In [29]:
s

array([ 0, 69, 69, 69, 69, 69, 69, 69, 69, 69, 69, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#Use copy memthod in array for copy

In [31]:
aq=np.array([[12,13,45],
         [43,342,21],
         [65,57633,2]])

#Two dimensional matrix

In [32]:
aq[2][1]

57633

In [37]:
aq[1:,:]
aq[1,:2]


array([ 43, 342])

In [38]:
aq[:]

array([[   12,    13,    45],
       [   43,   342,    21],
       [   65, 57633,     2]])

In [39]:

aq[:2,:2]

array([[ 12,  13],
       [ 43, 342]])

In [44]:
m=np.arange(1,100)
bool_arr=m>69
bool_arr

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [45]:
m[bool_arr]

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86,
       87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [47]:
tm=np.arange(1,11,1)

In [48]:
tm*tm

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [52]:
tm-tm
tm//2

array([0, 1, 1, 2, 2, 3, 3, 4, 4, 5], dtype=int32)

In [58]:
import pandas as pd
data=[10,20,30]
arr=np.array(data)
label=['a','b','c']
d={'a':10,'b':20,'c':30}
a=pd.Series(data=d,index=label)
a

a    10
b    20
c    30
dtype: int64

In [61]:
pd.Series(data=label)

0    a
1    b
2    c
dtype: object

In [69]:
import pandas as pd
ser1=pd.Series([1,2,3,4],["USA","USSR","UK","CHINA"])
ser2=pd.Series([1,2,5,4],["USA","USSR","Pak","CHINA"])
ser2["Pak"]

ser1+ser2




CHINA    8.0
Pak      NaN
UK       NaN
USA      2.0
USSR     4.0
dtype: float64

In [80]:
import numpy as np
import pandas as pd
np.random.seed(101)
from numpy.random import randn
df=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z' ])
df


W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [85]:
# df['W']
# type(df)
df['new']=df['W']-df['X']

In [104]:
df.drop('new',axis=1,inplace=True)


KeyError: "['new'] not found in axis"

In [103]:
df['addition_of_z_And_y']=df['X']+df['Y']

KeyError: 'X'

In [102]:
df.drop('X',axis=1,inplace=True)
df

KeyError: "['X'] not found in axis"

In [110]:
#df.drop('W',axis=1,inplace=True)
df.drop('A',axis=0,inplace=True)

In [112]:
df.loc['D']

Y                     -0.933237
Z                      0.955057
addition_of_z_And_y   -1.692109
Name: D, dtype: float64

In [114]:
# df.iloc[]
df.iloc[2]

Y                     -0.933237
Z                      0.955057
addition_of_z_And_y   -1.692109
Name: D, dtype: float64

In [118]:
df.loc['C','Z']


-0.5890005332865824

In [121]:
df.loc[['C','D'],['Y','Z']]

Y         Z
C  0.528813 -0.589001
D -0.933237  0.955057

In [128]:
import numpy as np
from numpy.random import randn
import pandas as pd
np.random.seed(101)
newdf=pd.DataFrame(randn(5,4),['A','B','C','D','E'],['W','X','Y','Z'])
newdf

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [132]:
bool_=newdf>0

In [133]:
newdf[bool_]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118       NaN       NaN  0.605965
C       NaN  0.740122  0.528813       NaN
D  0.188695       NaN       NaN  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [135]:
newdf[newdf['W']>0]

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [136]:
df[df['Y']>0]

Y         Z  addition_of_z_And_y
C  0.528813 -0.589001             1.268936
E  2.605967  0.683509             4.584725

In [142]:
newdf[newdf['Z']<0][['X']]


X
C  0.740122

In [148]:
newdf[(newdf['X']>0) & (newdf['Y']>0)][['W','Y']]

W         Y
A  2.706850  0.907969
C -2.018168  0.528813
E  0.190794  2.605967

In [151]:
newdf.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [152]:
newdf.reset_index()

index         W         X         Y         Z
0     A  2.706850  0.628133  0.907969  0.503826
1     B  0.651118 -0.319318 -0.848077  0.605965
2     C -2.018168  0.740122  0.528813 -0.589001
3     D  0.188695 -0.758872 -0.933237  0.955057
4     E  0.190794  1.978757  2.605967  0.683509

In [165]:
string='A I S A S'.split()

In [166]:
string

['A', 'I', 'S', 'A', 'S']

In [164]:
newdf['states']=string

ValueError: Length of values does not match length of index

In [171]:
newdf['new']="A w A i S".split()

In [172]:
newdf

W         X         Y         Z new
A  2.706850  0.628133  0.907969  0.503826   A
B  0.651118 -0.319318 -0.848077  0.605965   w
C -2.018168  0.740122  0.528813 -0.589001   A
D  0.188695 -0.758872 -0.933237  0.955057   i
E  0.190794  1.978757  2.605967  0.683509   S

In [176]:
newdf.drop('new',axis=1)

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [177]:
pd.DataFrame(randn(1,1),['A'],['O'])

O
A  0.302665

In [178]:
newdf.set_index('X')

W         Y         Z new
X                                          
 0.628133  2.706850  0.907969  0.503826   A
-0.319318  0.651118 -0.848077  0.605965   w
 0.740122 -2.018168  0.528813 -0.589001   A
-0.758872  0.188695 -0.933237  0.955057   i
 1.978757  0.190794  2.605967  0.683509   S

In [179]:
newdf.reset_index()

index         W         X         Y         Z new
0     A  2.706850  0.628133  0.907969  0.503826   A
1     B  0.651118 -0.319318 -0.848077  0.605965   w
2     C -2.018168  0.740122  0.528813 -0.589001   A
3     D  0.188695 -0.758872 -0.933237  0.955057   i
4     E  0.190794  1.978757  2.605967  0.683509   S

In [181]:
newdf.drop('new',axis=1,inplace=True)

In [182]:
newdf

W         X         Y         Z
A  2.706850  0.628133  0.907969  0.503826
B  0.651118 -0.319318 -0.848077  0.605965
C -2.018168  0.740122  0.528813 -0.589001
D  0.188695 -0.758872 -0.933237  0.955057
E  0.190794  1.978757  2.605967  0.683509

In [183]:
print("Data Frames are horoses of Data Science")

Data Frames are horoses of Data Science


#Data Frame

In [189]:
outside=['G1','G1','G1','G2','G2','G2']
inside=[1,2,3,1,2,3]
outside_hier=list(zip(outside,inside))
outside_hier=pd.MultiIndex.from_tuples(outside_hier)

In [220]:
out=['Pakistan','Pakistan','Pakistan','Aus','Aus','Aus']
inside=["win","lose","tie","win","lose","tie"]
out_hier=list(zip(out,inside))
out_hier=pd.MultiIndex.from_tuples(out_hier)
ausdf=pd.DataFrame(randn(6,2),out_hier,["T20","ODI"])
ausdf.loc["Aus"].loc["tie"]
ausdf.index.names=["Country","num"]
ausdf.loc['Pakistan'].loc['tie']["T20"]
ausdf.loc["Aus"].iloc[:2]["ODI"]
ausdf.xs("win",level="num")

T20       ODI
Country                     
Pakistan  1.715950 -0.468756
Aus      -0.166646 -0.445873

In [191]:
outside_hier

MultiIndex(levels=[['G1', 'G2'], [1, 2, 3]],
           codes=[[0, 0, 0, 1, 1, 1], [0, 1, 2, 0, 1, 2]])

In [192]:
df_=pd.DataFrame(randn(6,2),outside_hier,["A","B"])
df_

A         B
G1 1  1.693723 -1.706086
   2 -1.159119 -0.134841
   3  0.390528  0.166905
G2 1  0.184502  0.807706
   2  0.072960  0.638787
   3  0.329646 -0.497104

In [195]:
df_.loc["G1"].iloc[2]

A    0.390528
B    0.166905
Name: 3, dtype: float64

In [224]:
dic={'A':[1,2,np.nan],"B":[12,np.nan,np.nan],"C":[6,4,np.nan]}
dtf=pd.DataFrame(dic)
dtf

A     B    C
0  1.0  12.0  6.0
1  2.0   NaN  4.0
2  NaN   NaN  NaN

In [227]:
dtf.dropna(axis=0)

A     B    C
0  1.0  12.0  6.0

In [229]:
dtf.dropna(thresh=2)

A     B    C
0  1.0  12.0  6.0
1  2.0   NaN  4.0

In [243]:
dtf.fillna(value="kuch to likh do")


A    B    C
0  1.0  1.0  1.0
1  2.0  2.0  2.0
2  1.5  1.5  1.5

In [246]:
dtf['A']=dtf.fillna(dtf['A'].mean())
# dtf["B"]=dtf.fillna(dtf['B'].mean())
# dtf['C']=dtf.fillna(dtf["C"].mean())
dtf


A    B    C
0  1.0  1.0  1.0
1  2.0  2.0  2.0
2  1.5  1.5  1.5

In [253]:
import numpy as np
import pandas as pd
data={"Company":["Google","Google","Google","Microsoft","Microsoft","Microsoft","IBM","IBM","IBM"],
      "Sales":[123,121,23,23,3,434,35,345,454]}
pdf=pd.DataFrame(data)
pdf.groupby("Company").mean()

Sales
Company              
Google      89.000000
IBM        278.000000
Microsoft  153.333333

In [256]:
pdf.groupby("Company").describe().transpose()["IBM"]

Sales  count      3.000000
       mean     278.000000
       std      217.386752
       min       35.000000
       25%      190.000000
       50%      345.000000
       75%      399.500000
       max      454.000000
Name: IBM, dtype: float64

In [279]:
import numpy as np
import pandas as pd
df1=pd.DataFrame({"A":['A0','A1','A2','A3'],
                   "B":["B0","B1","B2","B3"],
                     "C":["C0","C1","C2","C3"],
                     "D":["D0","D1","D2","D3"]},index=[0,1,2,3])

df2=pd.DataFrame({"A":['A0','A1','A2','A3'],
                   "B":["B4","B5","B6","B7"],
                     "C":["C4","C5","C6","C7"],
                     "D":["D4","D5","D6","D7"]},index=[4,5,6,7])

df3=pd.DataFrame({"A":['A8','A9','A10','A11'],
                   "B":["B8","B9","B10","B11"],
                     "C":["C8","C9","C10","C11"],
                     "D":["D8","D9","D10","D11"]},index=[8,9,10,11])

In [280]:
pd.concat([df1,df2,df3],axis=1)

A    B    C    D    A    B    C    D    A    B    C    D
0    A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1    A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2    A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3    A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
4   NaN  NaN  NaN  NaN   A0   B4   C4   D4  NaN  NaN  NaN  NaN
5   NaN  NaN  NaN  NaN   A1   B5   C5   D5  NaN  NaN  NaN  NaN
6   NaN  NaN  NaN  NaN   A2   B6   C6   D6  NaN  NaN  NaN  NaN
7   NaN  NaN  NaN  NaN   A3   B7   C7   D7  NaN  NaN  NaN  NaN
8   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A8   B8   C8   D8
9   NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   A9   B9   C9   D9
10  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A10  B10  C10  D10
11  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN  A11  B11  C11  D11

In [281]:
pd.merge(df1,df2,how="inner",on="A")

A B_x C_x D_x B_y C_y D_y
0  A0  B0  C0  D0  B4  C4  D4
1  A1  B1  C1  D1  B5  C5  D5
2  A2  B2  C2  D2  B6  C6  D6
3  A3  B3  C3  D3  B7  C7  D7

In [283]:
import pandas as pd
import numpy as np
n_df=pd.DataFrame({'col1':[1,2,3,4],'col2':[111,222,333,111],'col3':['a','b','c','d']})
n_df

col1  col2 col3
0     1   111    a
1     2   222    b
2     3   333    c
3     4   111    d

In [292]:
len(n_df['col2'].unique())

3

In [296]:
n_df[(n_df["col1"]>=2)& (n_df["col2"]==333)]

col1  col2 col3
2     3   333    c

In [297]:
def times2(x):
    return 2*x


In [301]:
n_df['col2'].apply(times2).iloc[2]

666

In [302]:
n_df['col1'].sum()

10

In [303]:
n_df.columns

Index(['col1', 'col2', 'col3'], dtype='object')

In [304]:
n_df.index

RangeIndex(start=0, stop=4, step=1)

In [305]:
n_df.sort_values('col2')
n_df.

col1  col2 col3
0     1   111    a
3     4   111    d
1     2   222    b
2     3   333    c

In [306]:
n_df.isnull()

col1   col2   col3
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False

In [307]:
n_df.pivot_table(values='col2',index=['col1'],columns=['col3'])

col3      a      b      c      d
col1                            
1     111.0    NaN    NaN    NaN
2       NaN  222.0    NaN    NaN
3       NaN    NaN  333.0    NaN
4       NaN    NaN    NaN  111.0

In [308]:
pwd

'C:\\Users\\awais qamar'

In [309]:
pwd


'C:\\Users\\awais qamar'

In [320]:
wfpd=pd.read_csv('apple.csv')

In [322]:
n_df.to_csv('Awais.csv',index=False)